MODULE MODI_COMPUTE_FRAC_ICE1D

INTERFACE

      SUBROUTINE COMPUTE_FRAC_ICE1D(KLON,KIDIA,KFDIA,HFRAC_ICE,PFRAC_ICE,PT,KSTPT,KSTSZ,PSTACK)

INTEGER           , INTENT(IN)    :: KLON
INTEGER           , INTENT(IN)    :: KIDIA
INTEGER           , INTENT(IN)    :: KFDIA
CHARACTER*1       , INTENT(IN)    :: HFRAC_ICE  
REAL, DIMENSION(KLON), INTENT(IN)    :: PT         
REAL, DIMENSION(KLON), INTENT(INOUT) :: PFRAC_ICE  
INTEGER           , INTENT(IN)    :: KSTSZ
INTEGER           , INTENT(IN)    :: KSTPT
REAL              , INTENT(INOUT) :: PSTACK (KSTSZ)

END SUBROUTINE COMPUTE_FRAC_ICE1D

END INTERFACE

END MODULE
