MODULE MODI_TH_R_FROM_THL_RT_1D

INTERFACE

#ifdef USE_ACC
!$acc routine (TH_R_FROM_THL_RT_1D) seq
#endif
      SUBROUTINE TH_R_FROM_THL_RT_1D(KLON,KIDIA,KFDIA,HFRAC_ICE,PFRAC_ICE,PP,        &
                                  PTHL, PRT, PTH, PRV, PRL, PRI,         &
                                  PRSATW, PRSATI,KSTPT,KSTSZ,PSTACK)

#include "temp.h"

INTEGER             , INTENT(IN) :: KLON
INTEGER             , INTENT(IN) :: KIDIA
INTEGER             , INTENT(IN) :: KFDIA
CHARACTER*1         , INTENT(IN) :: HFRAC_ICE
REAL, DIMENSION(KLON), INTENT(INOUT) :: PFRAC_ICE
REAL, DIMENSION(KLON), INTENT(IN) :: PP          
REAL, DIMENSION(KLON), INTENT(IN) :: PTHL    
REAL, DIMENSION(KLON),INTENT(IN)  :: PRT    
REAL, DIMENSION(KLON), INTENT(OUT):: PTH    
REAL, DIMENSION(KLON), INTENT(OUT):: PRV    
REAL, DIMENSION(KLON), INTENT(INOUT):: PRL    
REAL, DIMENSION(KLON), INTENT(INOUT):: PRI    
REAL, DIMENSION(KLON), INTENT(OUT)  :: PRSATW 
REAL, DIMENSION(KLON), INTENT(OUT)  :: PRSATI 
INTEGER             , INTENT(IN) :: KSTSZ
INTEGER             , INTENT(IN) :: KSTPT
REAL                , INTENT(INOUT):: PSTACK (KSTSZ)

END SUBROUTINE TH_R_FROM_THL_RT_1D

END INTERFACE

END MODULE
