MODULE MODI_COMPUTE_FRAC_ICE2D

INTERFACE

      SUBROUTINE COMPUTE_FRAC_ICE2D(KLON,KIDIA,KFDIA,KLEV,HFRAC_ICE,PFRAC_ICE,PT)

INTEGER             , INTENT(IN)    :: KLON
INTEGER             , INTENT(IN)    :: KIDIA
INTEGER             , INTENT(IN)    :: KFDIA
INTEGER             , INTENT(IN)    :: KLEV
CHARACTER*1         , INTENT(IN)    :: HFRAC_ICE 
REAL, DIMENSION(KLON,KLEV), INTENT(IN)    :: PT        
REAL, DIMENSION(KLON,KLEV), INTENT(INOUT) :: PFRAC_ICE 

END SUBROUTINE COMPUTE_FRAC_ICE2D

END INTERFACE

END MODULE
