MODULE MODI_COMPUTE_MF_CLOUD_DIRECT

INTERFACE

      SUBROUTINE COMPUTE_MF_CLOUD_DIRECT(KLON,KIDIA,KFDIA, KLEV, KKB, KKE, KKL, &
                                        &KKLCL, PFRAC_UP, PRC_UP, PRI_UP,&
                                        &PRC_MF, PRI_MF, PCF_MF)

INTEGER,                INTENT(IN)   :: KLON
INTEGER,                INTENT(IN)   :: KIDIA
INTEGER,                INTENT(IN)   :: KFDIA
INTEGER,                INTENT(IN)   :: KLEV
INTEGER,                INTENT(IN)   :: KKB            
INTEGER,                INTENT(IN)   :: KKE            
INTEGER,                INTENT(IN)   :: KKL            
INTEGER, DIMENSION(KLON),  INTENT(IN)   :: KKLCL          
REAL, DIMENSION(KLON,KLEV),   INTENT(IN)   :: PFRAC_UP       
REAL, DIMENSION(KLON,KLEV),   INTENT(IN)   :: PRC_UP,PRI_UP  
REAL, DIMENSION(KLON,KLEV),   INTENT(OUT)  :: PRC_MF, PRI_MF 
REAL, DIMENSION(KLON,KLEV),   INTENT(OUT)  :: PCF_MF         

END SUBROUTINE COMPUTE_MF_CLOUD_DIRECT

END INTERFACE

END MODULE
