MODULE MODI_COMPUTE_FRAC_ICE1D

INTERFACE
SUBROUTINE COMPUTE_FRAC_ICE1D(KLON,HFRAC_ICE,PFRAC_ICE,PT)

INTEGER           , INTENT(IN)    :: KLON
CHARACTER*1       , INTENT(IN)    :: HFRAC_ICE  
REAL, DIMENSION(KLON), INTENT(IN)    :: PT         
REAL, DIMENSION(KLON), INTENT(INOUT) :: PFRAC_ICE  

END SUBROUTINE COMPUTE_FRAC_ICE1D
END INTERFACE

END MODULE
