MODULE MODI_COMPUTE_FRAC_ICE2D

INTERFACE

#ifdef USE_ACC
!$acc routine (COMPUTE_FRAC_ICE2D)
#endif
      SUBROUTINE COMPUTE_FRAC_ICE2D(KLON,KIDIA,KFDIA,KLEV,HFRAC_ICE,PFRAC_ICE,PT,KSTPT,KSTSZ,PSTACK)

#include "temp.h"

INTEGER             , INTENT(IN)    :: KLON
INTEGER             , INTENT(IN)    :: KIDIA
INTEGER             , INTENT(IN)    :: KFDIA
INTEGER             , INTENT(IN)    :: KLEV
CHARACTER*1         , INTENT(IN)    :: HFRAC_ICE 
REAL, DIMENSION(KLON,KLEV), INTENT(IN)    :: PT        
REAL, DIMENSION(KLON,KLEV), INTENT(INOUT) :: PFRAC_ICE 
INTEGER             , INTENT(IN)    :: KSTSZ
INTEGER             , INTENT(IN)    :: KSTPT
REAL                , INTENT(INOUT) :: PSTACK (KSTSZ)

END SUBROUTINE COMPUTE_FRAC_ICE2D

END INTERFACE

END MODULE
