SUBROUTINE SHALLOW_MF_LOAD_ALL (CDNAME)

USE LOAD_MOD, ONLY : OPEN_LOAD, CLOSE_LOAD, ILUN_IN, LOAD
IMPLICIT NONE

CHARACTER (LEN=*) :: CDNAME

LOGICAL, SAVE :: LLDONE = .FALSE.
INTEGER :: IDUM

IF (.NOT. LLDONE) THEN
  CALL OPEN_LOAD (CDNAME)
  CALL LOAD_MODD_NEB
  CALL LOAD_MODD_CST
  CALL LOAD_MODD_CMFSHALL
  CALL LOAD_MODD_CTURB
  CALL CLOSE_LOAD
ENDIF

LLDONE = .TRUE.

CONTAINS

SUBROUTINE LOAD_MODD_NEB

USE MODD_NEB

CALL LOAD (ILUN_IN, XTMINMIX)
CALL LOAD (ILUN_IN, XTMAXMIX)

END SUBROUTINE

SUBROUTINE LOAD_MODD_CTURB

USE MODD_CTURB

CALL LOAD (ILUN_IN, XCMFS)
CALL LOAD (ILUN_IN, XCMFB)
CALL LOAD (ILUN_IN, XCSHF)
CALL LOAD (ILUN_IN, XCHF)
CALL LOAD (ILUN_IN, XCTV)
CALL LOAD (ILUN_IN, XCHV)
CALL LOAD (ILUN_IN, XCHT1)
CALL LOAD (ILUN_IN, XCHT2)
CALL LOAD (ILUN_IN, XCPR1)
CALL LOAD (ILUN_IN, XCPR2)
CALL LOAD (ILUN_IN, XCPR3)
CALL LOAD (ILUN_IN, XCPR4)
CALL LOAD (ILUN_IN, XCPR5)
CALL LOAD (ILUN_IN, XCET)
CALL LOAD (ILUN_IN, XCDP)
CALL LOAD (ILUN_IN, XCDD)
CALL LOAD (ILUN_IN, XCDT)
CALL LOAD (ILUN_IN, XTKEMIN)
CALL LOAD (ILUN_IN, XLINI)
CALL LOAD (ILUN_IN, XLINF)
CALL LOAD (ILUN_IN, XALPSBL)
CALL LOAD (ILUN_IN, XASBL)
CALL LOAD (ILUN_IN, XCEP)
CALL LOAD (ILUN_IN, XA0)
CALL LOAD (ILUN_IN, XA2)
CALL LOAD (ILUN_IN, XA3)
CALL LOAD (ILUN_IN, XA5)
CALL LOAD (ILUN_IN, XCTD)
CALL LOAD (ILUN_IN, XCTP)
CALL LOAD (ILUN_IN, XPHI_LIM)
CALL LOAD (ILUN_IN, XSBL_O_BL)
CALL LOAD (ILUN_IN, XFTOP_O_FSURF)
CALL LOAD (ILUN_IN, LHARAT)

END SUBROUTINE

SUBROUTINE LOAD_MODD_CMFSHALL

USE MODD_CMFSHALL

CALL LOAD (ILUN_IN, XALP_PERT)
CALL LOAD (ILUN_IN, XABUO)
CALL LOAD (ILUN_IN, XBENTR)
CALL LOAD (ILUN_IN, XBDETR)
CALL LOAD (ILUN_IN, XCMF)
CALL LOAD (ILUN_IN, XENTR_MF)
CALL LOAD (ILUN_IN, XCRAD_MF)
CALL LOAD (ILUN_IN, XENTR_DRY)
CALL LOAD (ILUN_IN, XDETR_DRY)
CALL LOAD (ILUN_IN, XDETR_LUP)
CALL LOAD (ILUN_IN, XKCF_MF)
CALL LOAD (ILUN_IN, XKRC_MF)
CALL LOAD (ILUN_IN, XTAUSIGMF)
CALL LOAD (ILUN_IN, XPRES_UV)
CALL LOAD (ILUN_IN, XALPHA_MF)
CALL LOAD (ILUN_IN, XSIGMA_MF)
CALL LOAD (ILUN_IN, XFRAC_UP_MAX)
CALL LOAD (ILUN_IN, XA1)
CALL LOAD (ILUN_IN, XB)
CALL LOAD (ILUN_IN, XC)
CALL LOAD (ILUN_IN, XBETA1)
CALL LOAD (ILUN_IN, XR)
CALL LOAD (ILUN_IN, XLAMBDA)

END SUBROUTINE

SUBROUTINE LOAD_MODD_CST

USE MODD_CST

CALL LOAD (ILUN_IN, XPI)
CALL LOAD (ILUN_IN, XDAY)
CALL LOAD (ILUN_IN, XSIYEA)
CALL LOAD (ILUN_IN, XSIDAY)
CALL LOAD (ILUN_IN, XKARMAN)
CALL LOAD (ILUN_IN, XLIGHTSPEED)
CALL LOAD (ILUN_IN, XPLANCK)
CALL LOAD (ILUN_IN, XBOLTZ)
CALL LOAD (ILUN_IN, XAVOGADRO)
CALL LOAD (ILUN_IN, XRADIUS)
CALL LOAD (ILUN_IN, XOMEGA)
CALL LOAD (ILUN_IN, XG)
CALL LOAD (ILUN_IN, XP00)
CALL LOAD (ILUN_IN, XSTEFAN)
CALL LOAD (ILUN_IN, XI0)
CALL LOAD (ILUN_IN, XMD)
CALL LOAD (ILUN_IN, XMV)
CALL LOAD (ILUN_IN, XRD)
CALL LOAD (ILUN_IN, XRV)
CALL LOAD (ILUN_IN, XEPSILO)
CALL LOAD (ILUN_IN, XCPD)
CALL LOAD (ILUN_IN, XCPV)
CALL LOAD (ILUN_IN, XRHOLW)
CALL LOAD (ILUN_IN, XCL)
CALL LOAD (ILUN_IN, XCI)
CALL LOAD (ILUN_IN, XTT)
CALL LOAD (ILUN_IN, XLVTT)
CALL LOAD (ILUN_IN, XLSTT)
CALL LOAD (ILUN_IN, XLMTT)
CALL LOAD (ILUN_IN, XESTT)
CALL LOAD (ILUN_IN, XALPW)
CALL LOAD (ILUN_IN, XBETAW)
CALL LOAD (ILUN_IN, XGAMW)
CALL LOAD (ILUN_IN, XALPI)
CALL LOAD (ILUN_IN, XBETAI)
CALL LOAD (ILUN_IN, XGAMI)
CALL LOAD (ILUN_IN, XCONDI)
CALL LOAD (ILUN_IN, XTH00)
CALL LOAD (ILUN_IN, XRHOLI)
CALL LOAD (ILUN_IN, NDAYSEC)
CALL LOAD (ILUN_IN, RDSRV)
CALL LOAD (ILUN_IN, RDSCPD)
CALL LOAD (ILUN_IN, RINVXP00)

END SUBROUTINE

END SUBROUTINE

